### ISSUE TITLE
demo url please

### ISSUE THREAD

**Issue by johnfelipe** [KohoVolit/sayit.parldata.eu#1]
demo url please

**Comment by johnfelipe** [comment]
Hi again, please demo url

**Comment by girogiro** [comment]
Hi Felipe, sorry for the delay.
It will be up in a few days.

**Comment by johnfelipe** [comment]
Hi jaroslav please give me a little support for install your instance
https://github.com/KohoVolit/sayit.parldata.eu/issues/2

2015-02-23 6:05 GMT-05:00 Jaroslav Semančík notifications@github.com:

**Comment by girogiro** [comment]
Finally! URL of SayIt with Slovak parliament debates of the last 20 years is here:
http://nrsr.sk.sayit.parldata.eu

Another instance, for Serbian parliament (low quality data yet, but example of Cyrillic script):
http://skupstina.rs.sayit.parldata.eu

This project is a simpler use case of SayIt component than sayit.mysociety.org. There is no dynamic creation of instances and no web interface enabled whatsoever. On  the other hand, individual instances can have different localization settings.

Full text search is not configured yet.
