### ISSUE TITLE
how scrape and convert your data

### ISSUE THREAD

**Issue by johnfelipe** [KohoVolit/sayit.parldata.eu#10]
Do you use python or ruby

**Comment by girogiro** [comment]
Python 3.

Which data?

**Comment by johnfelipe** [comment]
Speakers, speeches, how conver them to xml?

**Comment by girogiro** [comment]
From which source in which format?

**Comment by johnfelipe** [comment]
Pdf

**Comment by johnfelipe** [comment]
Can you help me with that?

**Comment by girogiro** [comment]
You need a tool to get text content from PDF (eg. [pdftotext](http://en.wikipedia.org/wiki/Pdftotext)).

Then write a script to convert the obtained text to Akoma Ntoso XML as discussed in other issue. That script may be in Python, Ruby or any other language you are familiar with.
