### ISSUE TITLE
installation process issues

### ISSUE THREAD

**Issue by johnfelipe** [KohoVolit/sayit.parldata.eu#2]
When **(sayit)$ sudo pip install -r requirements.txt** I have this issue:

```
  Downloading Django-Select2-Py3-4.2.1.tar.gz (90kB): 90kB downloaded
  Running setup.py (path:/tmp/pip_build_root/Django-Select2-Py3/setup.py) egg_info for package Django-Select2-Py3
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/Django-Select2-Py3/setup.py", line 75
        % (fn, pattern)), file=sys.stderr)
                              ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/Django-Select2-Py3/setup.py", line 75

    % (fn, pattern)), file=sys.stderr)

                          ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/Django-Select2-Py3
Storing debug log for failure in /home/notroot/.pip/pip.log
```

**Comment by johnfelipe** [comment]
fix with https://github.com/mysociety/sayit.mysociety.org/issues/77#issuecomment-64170756

**Comment by johnfelipe** [comment]
Hi again
in **sudo pip install python-dateutil lxml**

	compilation terminated.

	error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

	----------------------------------------
	Cleaning up...
	Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pjqTBO-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
	Storing debug log for failure in /home/notroot/.pip/pip.log

**Comment by johnfelipe** [comment]
hello, pls tell me about my issue i have a instance: http://concejodemedellin.felipeurrego.com/
I want compare your changes with mysociety

**Comment by girogiro** [comment]
There were substantial changes in the repository last two weeks, if you are installing, pull the current state of the repo.

Nevertheless, I guess your issue could be caused by installation of Django Select2 package for Python 3 while running the setup in Python 2...?

This project requires Python 3 and Django 1.7.1+.
