### ISSUE TITLE
Installation process in CENTOS

### ISSUE THREAD

**Issue by johnfelipe** [KohoVolit/sayit.parldata.eu#3]
Installation process in CENTOS
Tnks

**Comment by girogiro** [comment]
I don't have Centos available, but the installation should be pretty similar to Ubuntu that the manual is for. I expect just the installation of packages to use a different package management system and there is a different way of managing permissions than `sudo` command on Centos, I think.

**Comment by johnfelipe** [comment]
https://gist.github.com/johnfelipe/cbb2b693ca89ff09bf1e, but im stagnant

**Comment by girogiro** [comment]
I don't know Centos, so only one note - you installed Python 2.7 but sayit.parldata.eu needs Python 3.
