### ISSUE TITLE
About thumbnails to work correctly

### ISSUE THREAD

**Issue by johnfelipe** [KohoVolit/sayit.parldata.eu#4]
In sayit about thumbnails i have an issue:

/home/notroot/sayit/virtualenv-sayit/src/django-sayit/speeches/templates/speeches/speaker_detail.html, edit this:

<img src="{% if speaker.image_cache %}{{ **MEDIA_URL** }}{{speaker.image_cache }}{% elif speaker.image %}{{ speaker.image }}{% else %}{% static "speeches/i/a.png" %}{% endif %}"

And speaker_list, speech and all templates because, https://github.com/mysociety/sayit.mysociety.org/issues/89. please tell me how fix it?

**Comment by girogiro** [comment]
It's a SayIt application issue not this project's one and I really don't know more than Matthew wrote in  mysociety/sayit.mysociety.org#89.

Try delete `/uploads` subdir, reimport all data and reload the page (making sure that it is not served from browser cache, but really reloaded).
