### ISSUE TITLE
how put speeches like you

### ISSUE THREAD

**Issue by johnfelipe** [KohoVolit/sayit.parldata.eu#6]
http://sejm.pl.sayit.parldata.eu/speeches
In akoma ntoso?

**Comment by girogiro** [comment]
Sections are shown this way using a custom view _RecentView_ (in `sayit_parldata_eu/views.py`) instead of _ParentlessView_ class that is default in SayIt app. It uses template `sayit_parldata_eu/templates/speeches/recent_view.py` and needs to be mapped in `sayit_parldata_eu/urls.py` instead of the default _ParentlessView_.

Here is a cleaner example:
http://nrsr.sk.sayit.parldata.eu/speeches

**Comment by johnfelipe** [comment]
How add this functional to original sayit?

**Comment by girogiro** [comment]
See the previous comment.

**Comment by johnfelipe** [comment]
But in akoma ntoso need something different?  Or add new field?

**Comment by johnfelipe** [comment]
http://concejodemedellin.felipeurrego.com/speeches, with repo of mysociety, please help me with that longer list
I do this:
/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/urls.py

```
from views import ShareWithCollaborators, AcceptInvite
from speeches.views import InstanceView, SpeakerList, SpeakerView, SectionView
from .views import RecentView
```

/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/views.py

```
from speeches.models import Section
from speeches.views import ParentlessList

class RecentView(ParentlessList):
    template_name = 'speeches/recent_view.html'

    def get_context_data(self, **kwargs):
        context = super(ParentlessList, self).get_context_data(**kwargs)

        qs = Section.objects.for_instance(self.request.instance)
        context['term_list'] = qs.filter(parent=None).order_by('-start_date', '-start_time')[:]
        if context['term_list']:
            current_term = context['term_list'][0]
            context['session_list'] = qs.filter(parent=current_term).order_by('-start_date', '-start_time')[:5]
            if context['session_list']:
                current_session = context['session_list'][0]
                context['sitting_list'] = qs.filter(parent=current_session).order_by('-start_date', '-start_time')
        return context
```

and add

/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/templates/speeches/recent_view.html

But same results

**Comment by girogiro** [comment]
And would you like your result to look like? Your have a number of debates in different days and I see no key how to group them in a tree. Hence a long list.

If you can group them within some sessions, make a two-level hierarchy in your Akoma Ntoso files - each Act section should be within a Session section. Follow the documentation http://sayit.mysociety.org/about/developers

**Comment by johnfelipe** [comment]
into header is possible?
**2013. ACTA 199, 1.3.2013**?

**Comment by girogiro** [comment]
No, use `<debateSection>` tags as in source
http://shakespeare.sayit.mysociety.org/king-lear.an
and its result
http://shakespeare.sayit.mysociety.org/king-lear

**Comment by johnfelipe** [comment]
```
<debateSection>
    <heading>YEAR</heading>
    <debateSection>
        <heading>MONTH</heading>
        <debateSection>
            <heading>DAY. MONTH. YEAR</heading>
            <debateSection>
                <heading>NAME OF HANSARD - ACTA 205</heading>
```

Its possible?

**Comment by girogiro** [comment]
Exactly.

Maybe, it's better to join the two innermost sections into one "Acta NNN, DD. MM. YYYY" and have only three levels of hierarchy if there is always only one transcript in a day.

**Comment by johnfelipe** [comment]
```
<debatebody>
  <debatesection>
    <heading>2012</heading>
    <debatesection>
      <heading>7</heading>
      <debatesection>
        <heading>25.7.2012</heading>
        <debatesection>
          <heading>ACTA No. 01</heading>
```

May be one or two hansard at day, this format is fine?

**Comment by girogiro** [comment]
The 3-level hierarchy 

``` xml
<debatebody>
  <debatesection>
    <heading>2012</heading>
    <debatesection>
      <heading>7</heading>
      <debatesection>
        <heading>ACTA No. 01, 25.7.2012</heading>
```

is better for user is there is only 1-2 debates per day. It saves one click to read the actual debate.

**Comment by johnfelipe** [comment]
This is my script
https://github.com/fernandouval/actas-consejo-medellin/blob/master/scrape.py
But 
https://gist.github.com/johnfelipe/681ae9854666752c85eb
Repeat NAME OF ACTA
Please tell me how solved that
Tnks so much

**Comment by johnfelipe** [comment]
This is xml generated

https://github.com/johnfelipe/hierarchyactasconcejodemedellin

But upload with akomantoso command:

![1](https://cloud.githubusercontent.com/assets/428820/7972195/2637bf0a-0a10-11e5-97ba-ae61acc70980.png)

![2](https://cloud.githubusercontent.com/assets/428820/7972203/34c817f4-0a10-11e5-9b63-3d7b3ed5f0f8.png)

Why?
Please tell me how fix it?

**Comment by girogiro** [comment]
Use `--merge-existing` option in the `load_akomantoso` command. This will merge a new section with duplicate name into the existing one resulting in only one _2013_ section.

Without this option a new duplicate section is created with the same name for every imported file.
